FROM docker.io/library/nginx:latest

LABEL maintainer="Naing Ye Minn <naingyeminn@gmail.com>"

COPY ./configre-api.sh /docker-entrypoint.d/
COPY resources /usr/share/nginx/html/resources
COPY ./index.html /usr/share/nginx/html/
