apiVersion: v1
data:
  mysql_password: {{ default "dbuser@123" .Values.db.password | b64enc | quote }}
  mysql_user: {{ default "dbuser" .Values.db.username | b64enc | quote }}
  root_password: {{ default "root@123" .Values.db.root_password | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  labels:
    app: todo-app
    {{- include "todo-app.labels" . | nindent 4 }}
