apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-db
    {{- include "todo-app.labels" . | nindent 4 }}
  name: {{ include "todo-app.fullname" . }}-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: todo-db
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
  type: ClusterIP
