apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-api
    {{- include "todo-app.labels" . | nindent 4 }}
  name: {{ include "todo-app.fullname" . }}-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: todo-api
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
  type: ClusterIP
